### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by xhyrom** [WekyDev/weky-npm#26]
Convert quick.db database to [keyv](https://www.npmjs.com/package/keyv) which supports multiple databases like sqlite, mysql, mongodb and more and is so simple too.

**Comment by sujalgoel** [comment]
Well, the aim of using quick.db was to save the winner's id by taking gameID as an input. So, the way of storing data isn't really necessary because it just returns the winner id and was intentioned that it will be deleted by the user after storing the data somewhere else.

**Comment by Tomato6966** [comment]
Or josh... but maybe try to do all of that just with pure json maybe?

**Comment by Assassin-1234** [comment]
json has tons of flaws like corruption of data. It wont work with a package anyways since it would be created inside node_modules which will erase while updating / removing / adding a new package.

**Comment by Tomato6966** [comment]
Not if you are doing it right

**Comment by Tomato6966** [comment]
It does not need to be created inside nodew_modules if done right
const path = process.cwd() + `/weky-data.json`

**Comment by xhyrom** [comment]
> 
> 
> Or josh... but maybe try to do all of that just with pure json maybe?

Keyv support mongodb, mysql, sqlite, json and more

**Comment by Tomato6966** [comment]
Yeah
