### ISSUE TITLE
Dokumentation missing

### ISSUE THREAD

**Issue by Tomato6966** [WekyDev/weky-npm#29]
I dont need them but beginners do!
Add a clear Dokumentation...

**Comment by rayzdev** [comment]
We were working on one. Not sure if we are going to finish soon because of some internal problems.

**Comment by Assassin-1234** [comment]
we do have a clear and deployed documentation [linked in readme] at https://weky-docs.sujalgoel.repl.co/. Although I'm not sure if that would be maintained because of some internal problems

**Comment by rayzdev** [comment]
> we do have a clear and deployed documentation [linked in readme] at https://weky-docs.sujalgoel.repl.co/. Although I'm not sure if that would be maintained because of some internal problems

Those docs are unfinished.

**Comment by Assassin-1234** [comment]
its in the readme tho
