### ISSUE TITLE
@weky/inlinereply

### ISSUE THREAD

**Issue by BranGamer145** [WekyDev/weky-npm#30]
**@weky/inlinereply** I entered it's actually an error' 🗿

**Comment by Assassin-1234** [comment]
what?

**Comment by hasib-rashid** [comment]
Did you install `@weky/inlinereply` If not then install it. Otherwise just remove the line

**Comment by rayzdev** [comment]
@BranGamer145 Please describe your error and include a screenshot of it. If it is something that `options.message.inlineReply is not a function` then join our support server. https://discord.gg/7TUxkQT9Bp

**Comment by rayzdev** [comment]
And also if you join the discord for help please close this issue.

**Comment by BranGamer145** [comment]
> @BranGamer145 Please describe your error and include a screenshot of it. If it is something that `options.message.inlineReply is not a function` then join our support server. https://discord.gg/7TUxkQT9Bp

Oh ok thanks

**Comment by BranGamer145** [comment]
> Did you install `@weky/inlinereply` If not then install it. Otherwise just remove the line

but now I have solved that error :D
