### ISSUE TITLE
Fight and Rock Paper sicorrs

### ISSUE THREAD

**Issue by HananJ123** [WekyDev/weky-npm#32]
Both games don't work. By fight happens nothing and at Rock Paper Sicorrs the mentioned message comes but no accept or decline button 
![image](https://user-images.githubusercontent.com/86073578/126560134-2a1e39a6-ee5d-4977-96da-420ab22a7185.jpeg)

**Comment by Assassin-1234** [comment]
make sure you have `require(discord-buttons)(client)` after your client declaration.

**Comment by HananJ123** [comment]
> make sure you have `require(discord-buttons)(client)` after your client declaration.

I do. The other commands for example calculator, snake etc. Work. Only fight and Rock Paper Scissors has an issue
