### ISSUE TITLE
Calculator Doesn't Work

### ISSUE THREAD

**Issue by NotTimIsReal** [WekyDev/weky-npm#33]
When I use the calculator I get the error `(node:23572) UnhandledPromiseRejectionWarning: TypeError: options.message.inlineReply is not a function`. I have used the code from the example code section

**Comment by NotTimIsReal** [comment]
I only got the package today

**Comment by HananJ123** [comment]
You need to download @weky/inlinereply (npm i @weky/inlinereply) 

And after paste under const Discord = require("discord.js"); this: 
require('@weky/inlinereply');

**Comment by NotTimIsReal** [comment]
> (npm i @weky/inlinereply

But I already have downloaded discord.reply

**Comment by dannyhpy** [comment]
Once you have downloaded **@weky/inlinereply** using _npm_,
you need to add the following line into your code (as suggested by _HananJ123_)
```js
require('@weky/inlinereply')
```

<hr>

**Comment by NotTimIsReal** [comment]
Thanks, that was the fix.
