### ISSUE TITLE
DJS V13 / Dev update

### ISSUE THREAD

**Issue by H4RDY-DEV** [WekyDev/weky-npm#36]
Is there any clarification that you will be making a v13 branch that will work amonst the djs package without `discord-buttons` ?

**Comment by face-hh** [comment]
Hello **DJHARDY2K21**, yes, we will rewrite to v13 our package as soon as `discord.js` launch v13 **officially** because i already have a lot of projects to work on!

**Comment by KingCh1ll** [comment]
@face-hh Hi! Discord.js v13 has released, and I decided to rewrite this package to support v13. Here's the open sourced github. https://kingch1ll/weky-npm-v13

**Comment by onyx-nxt** [comment]
They published it can you update it?
