### ISSUE TITLE
Discord.js v13 Compatibility

### ISSUE THREAD

**Issue by KingCh1ll** [WekyDev/weky-npm#40]
Hi! I created a github repo to support Discord.js v13 for weky.

**GitHub Repo Link**
https://github.com/kingch1ll/weky-npm-v13

**Comment by KingCh1ll** [comment]
The module, `Discord-buttons` doesn't work with Discord.js v13 and is pointless at that (since Discord v13 supports it). I removed it and replaced it with Discord v13.

**Comment by RaZeSloth** [comment]
Why not fork this repo and make a PR? It is kinda confusing on why make a whole new repo

**Comment by sujalgoel** [comment]
> Why not fork this repo and make a PR? It is kinda confusing on why make a whole new repo

yep

**Comment by KingCh1ll** [comment]
> Why not fork this repo and make a PR? It is kinda confusing on why make a whole new repo

I tried to do so. It gave me an odd error.

**Comment by sujalgoel** [comment]
> > Why not fork this repo and make a PR? It is kinda confusing on why make a whole new repo
> 
> I tried to do so. It gave me an odd error.

what is that error?

**Comment by KingCh1ll** [comment]
> > > Why not fork this repo and make a PR? It is kinda confusing on why make a whole new repo
> > 
> > 
> > I tried to do so. It gave me an odd error.
> 
> what is that error?

I don't really remember to be honest. It's been almost 4 days after all.

**Comment by rayzdev** [comment]
I took a look at the Calculator command on your repo. It's not working with v13. You are still using `.setID` instead of `.setCustomId`.

**Comment by rayzdev** [comment]
Yeah um you basically just removed discord-buttons and added `MessageButton` and `MessageActionRow` imports for discord.js. This won't work with discord.js v13.
