### ISSUE TITLE
Release v13 of Discord.js

### ISSUE THREAD

**Issue by hasib-rashid** [WekyDev/weky-npm#46]
Hey there, It would be very grateful if the team releases the package with discord version 13. As I can see here. Weky is still on DJS Version 12 of the npm package. But in the current Source code it has Version 13. Please release the current source code.

Here are some screenshots on weky being on version 12
![image](https://user-images.githubusercontent.com/69360193/131259298-89e863fa-8f01-487d-9ff2-c304c348b0eb.png)
![image](https://user-images.githubusercontent.com/69360193/131259310-fd8b2a5f-6b90-47d3-99f5-1c100ad3006f.png)

This is the actual Github source Code (please release it)
![image](https://user-images.githubusercontent.com/69360193/131259339-b3e237f0-52b6-468f-bcd2-ec946647b0b1.png)

Thank you for making this brilliant package ❤️

**Comment by hasib-rashid** [comment]
It is still using Discord Buttons which are somewhat causing hazards

**Comment by sujalgoel** [comment]
That stuff is incomplete.

**Comment by hasib-rashid** [comment]
Thank you very much for replying. Take your time guys
