### ISSUE TITLE
Sqlite3 doesn't support node v16 but djs v13 requires node v16.6.0 or higher

### ISSUE THREAD

**Issue by PixelPasta** [WekyDev/weky-npm#61]
When installing weky, npm also tries to imstall sqlite 3 which doesn't support node 16.x.x But It is requires for discord.js to be run on node 16.6.0 or higher? 

Because of this, an error occurs and weky doesn't get installed

**Comment by face-hh** [comment]
Can you send the error here so i can see the whole error message?

**Comment by PixelPasta** [comment]
![image](https://user-images.githubusercontent.com/80410384/138721944-05e1a572-902f-4828-ba81-6ee0e81243c0.png)
![image](https://user-images.githubusercontent.com/80410384/138721998-62402d83-15a4-4b2f-bbdd-be1a7f29fd03.png)
This error only occurs at the end of the installation. I already have Desktop development with C++ 2019 installed on my computer

**Comment by face-hh** [comment]
You can search that error up because i have honestly no idea what is it about, i also had similar errors about sql, python and node-pre-gyp, i had to get a better node version but ended up using a VM because i am on Windows 7 which doesn't support higher node version.

**Comment by PixelPasta** [comment]
I've tried each an every solution provided on google and it doesn't work, you really have no solution? Weky is a great package and it would be really useful for my bot

**Comment by ghost** [comment]
The error says that node-gyp can't find a visual studio installation to use. You should try following: https://stackoverflow.com/a/63311413

**Comment by PixelPasta** [comment]
the installation says its deprecated and its always stuck (it never installs completely and it fails). This didnt work

**Comment by onyx-nxt** [comment]
Sqlite3 now supports v16 right now. (tested on v`16.10.0`)
