### ISSUE TITLE
FetchError when trying to use WouldYouRather

### ISSUE THREAD

**Issue by nullsoepic** [WekyDev/weky-npm#63]
<h3>Description</h3>
When attempting to use the WouldYouRather function, a FetchError occurs and crashes the bot.

<h3>Expected behaviour:</h3>
Command runs successfully, and the bot replies with the game embed

<h3>Actual behaviour:</h3>
The command crashes the bot and outputs an error in the console indicating that it could not get a response from the api

<h3>Error:</h3>

`FetchError: request to https://fun-api.sujalgoel.engineer/wyr failed, reason: getaddrinfo ENOTFOUND fun-api.sujalgoel.engineer`

<h3>Other</h3>

Other commands seem to work without any issues

<h1>Edit</h1>
Same error occurs when using GuessThePokemon

**Comment by tvhsin** [comment]
@sujalgoel, Is fun-api.sujalgoel.engineer deprecated?

**Comment by sujalgoel** [comment]
> @sujalgoel, Is fun-api.sujalgoel.engineer deprecated?

The API doesn't exist. So, it's better not to use weky functions that calls `fun-api.sujalgoel.engineer`.
