### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by PixelPasta** [WekyDev/weky-npm#64]
How do I fix this. Im using v13
![image](https://user-images.githubusercontent.com/80410384/142614244-e1bb2c14-f542-42ce-adeb-f714279bbe4a.png)

**Comment by KingCh1ll** [comment]
Discord.js v13 has their own buttons update. Therefore, discord-buttons doesn't work anymore.

**Comment by KingCh1ll** [comment]
To fix this, you should remove discord-buttons.

**Comment by Tomato6966** [comment]
```
npm uninstall discord-buttons
```

close this issue^^
