### ISSUE TITLE
Is this package still maintained by any chance

### ISSUE THREAD

**Issue by ChrisSch-dev** [WekyDev/weky-npm#74]
Is this package maintained by any chance?

**Comment by ddodogames** [comment]
well, to answer your question, it has been deprecated on npm page
![image](https://user-images.githubusercontent.com/69091682/173030853-7b4d85d3-8992-4203-a016-0787df6c7929.png)

**Comment by ddodogames** [comment]
however, you can fork it and maintain it yourself, there have been a few people who's maintaining it on their npm pages
